# Issue \#4
---

https://github.com/UoS-SNe/LSST_tools/issues/4

---

When simulating, the numbers of similated SNID's and SNNames don't match:

```
> output_df["snname"].value_counts()
SN2005bf    7834
SN1993J     1877
SN1994I      289
Name: snname, dtype: int64
``` 

and 
```
> output_df["snindex"].value_counts()
23    746
9     745
6     745
18    739
24    727
17    711
7     701
13    701
12    691
10    674
19    654
14    336
2     325
21    325
0     310
22    304
15    277
3      50
4      44
5      39
20     38
1      35
11     31
16     26
8      26
Name: snindex, dtype: int64
```
![snids_sdss_sesne_2](https://user-images.githubusercontent.com/10420166/27956030-b34cee24-630f-11e7-937e-808508f0fcb4.png)

---

## Current Implementation:

```
        ## Choose SN Type
        subtype = lsstt.sims.choose_subtype()
        if verbose: print(subtype)

        ## Choose SN
        w = np.where(info.table["Type"] == subtype)[0]
        snindex = np.random.choice(w)
        snname = pcc.utils.b(info.table["snname"].data[w][0])
        if verbose: print(w, snname)
```

In [19]:
%matplotlib inline

import os 
import json
import pandas as pd
import numpy as np

import pycoco as pcc
import lsst_tools as lsstt

In [7]:
verbose=True

Check infofile looks OK

In [12]:
info = pcc.InfoClass()
# info.load()
# use only good SNe
info.load(path = "/Users/berto/Code/CoCo/data/info/info_good.dat")

In [16]:
info.table.show_in_notebook()

Infofile looks fine - must be in the sims

In [25]:
## Choose SN Type
subtype = lsstt.sims.choose_subtype()
if verbose: print(subtype)

IIb


In [29]:
np.where(info.table["Type"] == subtype)[0]

array([ 0,  2, 14, 15, 21, 22])

In [23]:
w = np.where(info.table["Type"] == subtype)[0]
snindex = np.random.choice(w)
snname = pcc.utils.b(info.table["snname"].data[w][0])
if verbose: print(w, snname, snindex)

[ 6  7  9 10 12 13 17 18 19 23 24] b'SN2005bf' 12


There it is. I can actually remember the edit that caused it. 
`w` was being assigned the array, as `numpy.where` returns a tuple, in line 1 above.
`snindex` was being assigned correctly, but `snname` used `w`, rather than the index. Corrected, this should look like:

In [37]:
w = np.where(info.table["Type"] == subtype)[0]
snindex = np.random.choice(w)
snname = pcc.utils.b(info.table["snname"].data[snindex])
if verbose: print(w, snname, snindex)

[ 0  2 14 15 21 22] b'SN2011ei' 22


---
# Fixed